create table appuser (
    id INT GENERATED BY DEFAULT AS IDENTITY primary key,
    firstname varchar(50),
    lastname varchar(50),
    email varchar(50)
);

insert into appuser (firstname, lastname, email) values ('William','Britton','kingnathanal@gmail.com');

select * from appuser
